### ISSUE TITLE
Rename EventDescription

### ISSUE THREAD

**Issue by jahshuah** [splunk/TA-microsoft-sysmon#1]
In order to be more CIM compatible, would it make sense to rename (alias) the `EventDescription` field to `signature`, and the `EventCode` field to `signature_id`? It would marry up with what the `Splunk_TA_windows` app is doing.

**Comment by daveherrald** [comment]
Jahshuah,

Thanks for the suggestion.  Seems to make sense at first glance.  Let me dig in a bit and see if it's something we can do.  It may not be until November time-frame as this is a side-project for me.

**Comment by jahshuah** [comment]
No worries.  I created a TA for sysmon for my team on this project, so I've got some of the extractions already defined.  Let me know if sharing them might be of benefit.

**Comment by daveherrald** [comment]
We would love to see what you came up with and would absolutely consider including it with attribution to you and your team.

**Comment by daveherrald** [comment]
This is implemented. Please see: https://github.com/splunk/TA-microsoft-sysmon/commit/fb4877216e0347cd9f13963571f4741084735c68
