### ISSUE TITLE
Sysmon 5 released adding file and registry modification event types

### ISSUE THREAD

**Issue by dstaulcu** [splunk/TA-microsoft-sysmon#12]
i'll take a cut at changes and initiate pull requests
-./default/eventtypes.conf updated (to do)
-./lookups/eventcode.csv updated (to do)

**Comment by daveherrald** [comment]
Thanks @dstaulcu. Look forward to the pull request.

**Comment by dstaulcu** [comment]
Thanks.  I can’t seem to push.  Can you give dstaulcu contributor permissions?
