### ISSUE TITLE
Populate the process CIM field

### ISSUE THREAD

**Issue by daveherrald** [splunk/TA-microsoft-sysmon#15]
Consider the following CIM-compliant field extraction for "process":

EVAL-process = if(EventCode=="1", substr(CommandLine, 2, len(CommandLine)-2), Image)

**Comment by dstaulcu** [comment]
sourcetype=xmlwineventlog:microsoft-windows-sysmon/operational EventID=1
| rex field=_raw "Data Name='Image'>.*\\\(?<process>.*)<\/Data><Data Name='CommandLine'" 
| table _time EventID Image process

**Comment by dstaulcu** [comment]
`sourcetype=xmlwineventlog:microsoft-windows-sysmon/operational EventID=2
| rex field=_raw "Data Name='Image'>.*\\\(?<process>.*)<\/Data><Data Name='TargetFilename" `

**Comment by dstaulcu** [comment]
sourcetype=xmlwineventlog:microsoft-windows-sysmon/operational EventID=11
| rex field=_raw "Data Name='Image'>.*\\\(?<process>.*)<\/Data><Data Name='TargetFilename" 
| table _time EventID Image process _raw

**Comment by dstaulcu** [comment]
`sourcetype=xmlwineventlog:microsoft-windows-sysmon/operational  EventID=12
| rex field=_raw "Data Name='Image'>.*\\\(?<process>.*)<\/Data><Data Name='TargetObject" 
| table _time EventID Image process _raw`

**Comment by dstaulcu** [comment]
`sourcetype=xmlwineventlog:microsoft-windows-sysmon/operational  EventID=13
| rex field=_raw "Data Name='Image'>.*\\\(?<process>.*)<\/Data><Data Name='TargetObject" 
| table _time EventID Image process _raw`

**Comment by dstaulcu** [comment]
Definitely want CIM compliance but also cringe at idea of even more extractions for this very high volume data set.   Might be worth recommending a dedicated index and data-type specific index attribute for sysmon data for the benefit of performance.

**Comment by daveherrald** [comment]
Thanks @dstaulcu for all the work here!

**Comment by dstaulcu** [comment]
Question:  Is the objective to store the full path to the full path of the process in the process field, or just the process name?

**Comment by dstaulcu** [comment]
`sourcetype=xmlwineventlog:microsoft-windows-sysmon/operational | dedup EventID
| eval process = case(EventCode=="1" OR EventCode=="2" OR EventCode=="3" OR EventCode=="5" OR EventCode=="7" OR EventCode=="11" OR EventCode=="12" OR EventCode=="13" OR EventCode=="14", replace(Image,"(.*\\\)(?=.*(\.\w*)$|(\w+)$)",""),EventCode=="8" OR EventCode=="10",replace(SourceImage,"(.*\\\)(?=.*(\.\w*)$|(\w+)$)",""),1==1,"Undefined")
| table _time EventID EventDescription process  | sort EventID`

![image](https://cloud.githubusercontent.com/assets/6827994/20821869/3d08fdee-b814-11e6-9dfd-3e1f044e9324.png)

**Comment by dstaulcu** [comment]
Submitted a pull request for what I think it was you were looking for.. feelings wont be hurt if I missed the mark. it was the journey..

**Comment by daveherrald** [comment]
Wow you have been busy. I'll look at it on the plane this morning. Can't thank you enough!



DH

**Comment by daveherrald** [comment]
I accepted merged your pull request. Looking for some testing before I package it up and move to Splunkbase.

**Comment by dstaulcu** [comment]
We catch a lot of passwords in sysmon data.

 Ill submit a pull request soon having a sample SED based password position data masking transform.  This would require the app to be installed on HF or IDX such that masking rule is applied prior to indexing.

Sent from my iPhone

On Dec 5, 2016, at 10:10 AM, Dave Herrald <notifications@github.com<mailto:notifications@github.com>> wrote:

Wow you have been busy. I'll look at it on the plane this morning. Can't thank you enough!



DH
