### ISSUE TITLE
Update support for Sysmon v6

### ISSUE THREAD

**Issue by dstaulcu** [splunk/TA-microsoft-sysmon#19]

**Comment by daveherrald** [comment]
Accepted the pull request. Doing some final testing. Also need to update README and finally load to Splunkbase.

Thanks @dstaulcu as always for your contributions!

**Comment by dstaulcu** [comment]
Glad to contribute to DFIR community even if it's in this simple way.  So much creative stuff happening.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by daveherrald** [comment]
Version 6.0.0 published to SplunkBase

**Comment by dstaulcu** [comment]
app updated via web for me.  no apparent loss in functionality.  thanks!
