### ISSUE TITLE
New event codes with sysmon 3.2 release 1/4/2016

### ISSUE THREAD

**Issue by dstaulcu** [splunk/TA-microsoft-sysmon#2]
Suggested update for eventcode.csv:

EventCode,EventDescription
1,"Process Create"
2,"File Create Time"
3,"Network Connect"
**4,"Sysmon Start"**
5,"Process Terminate"
6,"Driver Load"
7,"Image Load"
8,"Create Remote Thread"
**9,"Raw Access Read"**
255,"Error"

**Comment by daveherrald** [comment]
Thanks for reporting. Traveling the next few weeks but will have a look as soon as I can.

**Comment by daveherrald** [comment]
Updated and checked in to master. Version 3.2.1 of this TA is forthcoming.

**Comment by dstaulcu** [comment]
Thanks!
