### ISSUE TITLE
Add support for new events in Sysmon v6.10

### ISSUE THREAD

**Issue by dstaulcu** [splunk/TA-microsoft-sysmon#26]
EventID 19: WmiEventFilter activity detected
EventType
UtcTime
Operation
User
EventNamespace
Name
Query

EventID=20: WmiEventConsumer activity detected
EventType
UtcTime
Operation
User
Name
Type
Destination

EventID=21: WmiEventConsumerToFilter activity detected
EventType
UtcTime
Operation
User
Consumer
Filter

**Comment by dstaulcu** [comment]
[Pull request](https://github.com/splunk/TA-microsoft-sysmon/pull/27) submitted

**Comment by daveherrald** [comment]
Pull reviewed, approved, and merged.

You sir, are awesome!
