### ISSUE TITLE
Eventtype mislabled? 

### ISSUE THREAD

**Issue by dstaulcu** [splunk/TA-microsoft-sysmon#3]
I see you have a stanza for network and and stanza for process, but the tag for both stanzas is for network.. -- a typo?

Here is a suggested update to eventtypes.conf, with additional event codes needed to support sysmon 3.2 released 1/4/2016.

[ms-sysmon-network]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" EventCode="3"
# tags = network

[ms-sysmon-process]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" (EventCode="1" OR EventCode="2" OR EventCode="5" OR EventCode="6" OR EventCode="7" OR EventCode="8" OR EventCode="9")
# tags = process

**Comment by daveherrald** [comment]
Thanks for reporting. Traveling the next few weeks but will have a look as soon as I can.

**Comment by daveherrald** [comment]
They are just comments, though perhaps somewhat confusing. The config that matters in tags.conf. Deleted these two comments and checked into master. Version 3.2.1 of this TA is forthcoming.
