### ISSUE TITLE
make better use of source metadata field

### ISSUE THREAD

**Issue by dstaulcu** [splunk/TA-microsoft-sysmon#33]
At present the source and sourcetype metadata fields values are identical.   Might be worth including the extracted value of EventID as part of the source meatadata field values (e.g. source=Sysmon:$EventID$) so that searches can be constructed to filter results from this dense more efficiently.

**Comment by dstaulcu** [comment]
I have a fork to address this in play and am currently testing it prior to submitting a pull request.   
https://github.com/dstaulcu/TA-microsoft-sysmon

**Comment by daveherrald** [comment]
Thanks David. I think this would conflict with what they are doing in the Windows TA v5. I will probably change the Sysmon TA to match. Doc link:

http://docs.splunk.com/Documentation/WindowsAddOn/5.0.0/User/Upgrade#Source_and_sourcetype_changes_for_WinEventLog_data

**Comment by dstaulcu** [comment]
That is a good point.  I had heard about that change in the windows add on (v5) but had not yet internalized it.
I’ve updated changes in my fork (also influences pull request) to prefix the source field with new convention but also to suffix the source field with the performance enhancing token.

[sysmon_source-eventid]
SOURCE_KEY = _raw
REGEX = <EventID>(\d+)</EventID>.*<Channel>(.+?)<\/Channel>.*
DEST_KEY = MetaData:Source
FORMAT = source::XmlWinEventLog:$2:$1

**Comment by daveherrald** [comment]
Hi David, we appreciate all your time and effort on this. There's no precedent that I'm aware of for overloading the source field to contain event field data in this way. We're probably not going to incorporate that part of the change into the TA.

**Comment by dstaulcu** [comment]
Completely understand.

Disruption in schema is coming one way or the other.  People are going to have to adapt their knowledge objects or behaviors due to windows add-on v5.  If we wanted to be bold with a change this would be the time to do it..

That said, It does feel hacky to append this info to the end of a source field.  In my mind the only alternative to achieve improved search times for non-accelerated searches would be to make the EventID an indexed field.  Adding an indexed field may also be unwelcome Symon data that is in an index shared with other sources.

Thanks for your time & thoughts on the matter.











________________________________
