### ISSUE TITLE
Invalid FIELDALIAS config

### ISSUE THREAD

**Issue by automine** [splunk/TA-microsoft-sysmon#38]
Splunk 7.2.5 will crash if it finds an invalid field alias configuration. Lucky day, there's one here!

`props.conf` line 35:

```
FIELDALIAS-process_current_directory = CurrentDirectory
```

Should read:
 
```
FIELDALIAS-process_current_directory = CurrentDirectory AS process_current_directory
```

Thanks!

Dave

**Comment by daveherrald** [comment]
Thanks Dave! I just updated that in the master branch.
