### ISSUE TITLE
More hashes than Amsterdam

### ISSUE THREAD

**Issue by fwijnholds** [splunk/TA-microsoft-sysmon#39]
Popular Sysmon config have this for log config: 
`<HashAlgorithms>*</HashAlgorithms>`

CIM compliance is achieved however by mapping CIM field process_hashes to the TA field hashes. Which will result in a hashes field containing all hashes. I have moved the mapping to SHA256 in my deployment. It is hard to automate against a multi value field. How would this work in real live?

**Comment by daveherrald** [comment]
We have tried it both ways in the past, and there is no way to satisfy everyone. Customizing for your needs as you have done is a fine way to deal with it.
