### ISSUE TITLE
Extract MD5 and SHA fields

### ISSUE THREAD

**Issue by daveherrald** [splunk/TA-microsoft-sysmon#4]
In my setups I have MD5 & SHA enabled to report back to Splunk. In the TA both values get reported under the HASHES field. 
 
By adding this line of regex in search:
index=* | rex field=_raw  "<Data Name='Hashes'>MD5=(?<MD5>\w+),SHA256=(?P<SHA256>\w+)</Data>”

This in the props.conf takes care of it in 
EXTRACT-hash = <Data Name='Hashes'>MD5=(?<MD5>\w+),SHA256=(?P<SHA256>\w+)</Data>

**Comment by fwijnholds** [comment]
The sysmon options are as follows; [-h <[sha1|md5|sha256|imphash|*]. By adding the options to the config they appear in the ordere as shown in the options listing. 

To extract this properly in every possible combination your extracts should look like this:
EXTRACT-md5 = MD5=(?<MD5>\w+)
EXTRACT-sha1 = SHA1=(?<SHA1>\w+)
EXTRACT-sha256 = SHA256=(?<SHA256>\w+)
EXTRACT-imphash = IMPHASH=(?<IMPHASH>\w+)

**Comment by daveherrald** [comment]
Added to version 3.2.2. Uploaded to Splunkbase.
